#version: '3'

services:
  client:
    build:
      context: ./client/
      dockerfile: ./docker/Dockerfile
    container_name: client
    working_dir: /usr/src/app
    volumes:
      - ./client:/usr/src/app
    ports:
      - '4200:4200'
    environment:
      - CHOKIDAR_USEPOLLING=true

  api:
    build:
      context: ./api
      dockerfile: ./docker/Dockerfile
    container_name: api
    volumes:
      - ./api:/var/www/html
    environment:
      - PHP_FPM_DB_PATH=/var/www/html/database/database.sqlite
    expose:
      - 9000
    command: sh -c "php-fpm"

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./client/src/:/usr/src/app/src
      - ./api/public:/var/www/html/public
    ports:
      - '8080:80'
    depends_on:
      - client
      - api

